# Generated by Django 4.2.5 on 2024-02-16 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_type_rename_date_stock_day_stock_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Symbol',
            field=models.ForeignKey(limit_choices_to={'TypeSector': django.db.models.expressions.OuterRef('Type')}, on_delete=django.db.models.deletion.CASCADE, to='Stock.symbol'),
        ),
    ]
