# Generated by Django 4.2.5 on 2024-02-16 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0005_alter_stock_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Symbol',
            field=models.ForeignKey(limit_choices_to={'TypeSector__TypeSector': django.db.models.expressions.OuterRef('Type__TypeSector')}, on_delete=django.db.models.deletion.CASCADE, to='Stock.symbol'),
        ),
    ]
