# Generated by Django 4.2.5 on 2024-02-16 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0006_alter_stock_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.symbol'),
        ),
    ]
