# Generated by Django 4.2.5 on 2024-03-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0007_alter_stock_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Symbol',
            new_name='Symbol_Ticker',
        ),
    ]
