# Generated by Django 4.2.5 on 2024-03-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0008_rename_symbol_stock_symbol_ticker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Stock_History',
        ),
    ]
