# Generated by Django 4.2.5 on 2024-03-24 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0010_stock_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Currency_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quarter_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dividend_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dividend_Per_Share', models.FloatField(default=0)),
                ('Before_TAX', models.FloatField(default=0)),
                ('Withholding_TAX', models.FloatField(max_length=255)),
                ('After_TAX', models.FloatField(default=0)),
                ('Amount_holding', models.FloatField(default=0)),
                ('Rate', models.FloatField(default=0)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Channel_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.channel')),
                ('Currency_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.currency')),
                ('Quarter_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.quarter')),
                ('Ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.stock_info')),
                ('Type_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.type')),
            ],
        ),
    ]
