# Generated by Django 4.2.5 on 2024-03-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0012_alter_dividend_history_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend_history',
            name='Ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.stock_info'),
        ),
    ]
