# Generated by Django 4.2.5 on 2024-03-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0014_alter_dividend_history_ticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ['-Symbolname']},
        ),
        migrations.AlterField(
            model_name='dividend_history',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dividend_history',
            name='Withholding_TAX',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='symbol',
            table='symbol',
        ),
    ]
