# Generated by Django 4.2.5 on 2024-03-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0015_alter_symbol_options_alter_dividend_history_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='symbol',
            table='Symbol',
        ),
    ]
